#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import textwrap

import pandas as pd
import nbformat as nbf


ROOT = Path(__file__).resolve().parents[2]
RUBRIC = ROOT / "outputs" / "modeling" / "rubric_completion"
FIG = "../../outputs/visualizations/reproducible_report_figures"
OUT = ROOT / "reports" / "final" / "SIADS_696_Team_7_Final_Report.ipynb"


def md(text: str):
    return nbf.v4.new_markdown_cell(textwrap.dedent(text).strip())


def simple_table(headers, rows):
    def esc(x):
        value = "" if pd.isna(x) else str(x)
        return value.replace("\n", " ").replace("|", "\\|")

    out = ["| " + " | ".join(esc(h) for h in headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(esc(v) for v in row) + " |")
    return "\n".join(out)


def fmt_num(x, digits=2):
    if pd.isna(x):
        return "--"
    return f"{float(x):.{digits}f}"


def load_tables():
    metrics = pd.read_csv(RUBRIC / "supervised_cv_metrics_with_sd.csv")
    ablation = pd.read_csv(RUBRIC / "rf_feature_family_ablation.csv")
    sensitivity = pd.read_csv(RUBRIC / "rf_sensitivity_grid.csv")
    failures = pd.read_csv(RUBRIC / "supervised_failure_examples.csv")
    unsup = pd.read_csv(RUBRIC / "unsupervised_method_comparison.csv")
    anova = pd.read_csv(RUBRIC / "unsupervised_fmd_anova.csv")
    features = pd.read_csv(RUBRIC / "rf_feature_importance.csv")
    search = pd.read_csv(RUBRIC / "unsupervised_method_search.csv")
    panel = pd.read_csv(ROOT / "data" / "processed" / "county_panel_enriched.csv")
    return metrics, ablation, sensitivity, failures, unsup, anova, features, search, panel


metrics, ablation, sensitivity, failures, unsup, anova, features, search, panel = load_tables()

panel_rows = f"{len(panel):,}"
panel_cols = f"{panel.shape[1]:,}"
county_count = f"{panel['geoid'].nunique():,}"
year_min = int(panel["year"].min())
year_max = int(panel["year"].max())
state_count = panel["state_name"].nunique()
daily_coverage = panel["daily_aqi_observed_days"].notna().mean() * 100
noaa_coverage = panel["annual_avg_temp_f"].notna().mean() * 100
best = metrics.sort_values("holdout_rmse").iloc[0]
baseline = metrics[metrics["model"].eq("Dummy mean baseline")].iloc[0]

metrics_rows = [
    [
        r.model,
        fmt_num(r.holdout_rmse),
        fmt_num(r.holdout_mae),
        fmt_num(r.holdout_r2),
        fmt_num(r.cv_rmse_mean),
        fmt_num(r.cv_rmse_sd),
        fmt_num(r.cv_r2_mean),
        fmt_num(r.cv_r2_sd),
    ]
    for r in metrics.itertuples(index=False)
]

ablation_rows = [
    [r.removed_family, int(r.features_removed), fmt_num(r.holdout_rmse), fmt_num(r.rmse_delta)]
    for r in ablation.itertuples(index=False)
]

sensitivity_rows = [
    [int(r.min_samples_leaf), r.max_features, fmt_num(r.holdout_rmse), fmt_num(r.holdout_r2)]
    for r in sensitivity.head(8).itertuples(index=False)
]

failure_rows = [
    [
        r.county_name,
        r.state_name,
        fmt_num(r.next_year_fmd),
        fmt_num(r.prediction),
        fmt_num(r.residual),
        r.failure_category,
    ]
    for r in failures.head(6).itertuples(index=False)
]

unsup_rows = [
    [
        r.method,
        r.params,
        int(r.clusters),
        fmt_num(r.noise_pct, 3),
        fmt_num(r.silhouette_embedding),
        fmt_num(r.silhouette_scaled_features),
    ]
    for r in unsup.itertuples(index=False)
]

anova_rows = [
    [r.method, fmt_num(r.f_stat), fmt_num(r.p_value, 4), int(r.groups)]
    for r in anova.itertuples(index=False)
]

feature_rows = [
    [r.feature, r.family, fmt_num(r.importance, 4)]
    for r in features.sort_values(["family", "feature"]).itertuples(index=False)
]

search_summary = (
    search.sort_values(["method", "silhouette_embedding"], ascending=[True, False])
    .groupby("method")
    .head(3)
)
search_rows = [
    [
        r.method,
        r.params,
        int(r.clusters),
        fmt_num(r.noise_pct, 3),
        fmt_num(r.silhouette_embedding),
        fmt_num(r.silhouette_scaled_features),
    ]
    for r in search_summary.itertuples(index=False)
]

cells = [
    md(
        f"""
        # Frequent Mental Distress Prediction Using Air Pollution

        **SIADS 696 Final Project Report | Team 7**  
        **Jaeah Kim, Kyle Rodriguez, Sophia Boettcher**

        **Report format note.** This notebook is written as the final report artifact. All report figures are loaded from `outputs/visualizations/reproducible_report_figures/`, which is regenerated by `notebooks/06_visualization_generation/Final_Report_Reproducible_Visualizations.ipynb` from project data and model-output CSVs.
        """
    ),
    md(
        """
        ## Introduction

        **Question: What problem are we trying to solve?**  
        **Answer:** We ask whether county-level air quality, climate, and socioeconomic features can help predict future community mental-health burden. The outcome is CDC PLACES frequent mental distress (FMD): the percentage of adults reporting poor mental health for 14 or more days in the past month.

        **Question: What impact would solving this problem have?**  
        **Answer:** If county-level signals can forecast next-year FMD even modestly, public-health agencies could use the results as planning signals for outreach, prevention, and behavioral-health capacity. We do not claim individual diagnosis or causality; the practical value is better identification of where additional support may be needed.

        **Question: What motivated this project?**  
        **Answer:** Prior literature links environmental exposures, socioeconomic conditions, and mental health, but fewer projects test whether public county-level data can support leakage-safe prediction and exploratory profiling. The team was motivated by the possibility that publicly available environmental and demographic data could help identify future mental-health need while also showing where those data are insufficient.

        **Question: What supervised and unsupervised methods did we use, and what is novel about our approach?**  
        **Answer:** The supervised task predicts next-year FMD from current-year features using Dummy, ElasticNet, Random Forest, and Gradient Boosting regressors. The unsupervised task compares DBSCAN and K-Means clusters using non-FMD features, then evaluates FMD after clustering as a held-out outcome. Compared with related studies focused on individual cohorts or single exposure families, our project combines pollution, climate, ACS socioeconomic features, health-access proxies, industry composition, and county geography in a county-year predictive/exploratory pipeline.
        """
    ),
    md(
        f"""
        **Question: What are the main findings?**  
        **Answer:** The best supervised model was **{best['model']}**, with holdout RMSE **{best['holdout_rmse']:.2f}** versus the Dummy baseline RMSE **{baseline['holdout_rmse']:.2f}**. This suggests weak predictive signal, but holdout R² remains near zero, so the model is not policy-ready. The unsupervised analysis found one dominant county group plus smaller outlier groups. DBSCAN was useful for identifying unusual counties, while K-Means produced cleaner silhouette scores but still imbalanced clusters.
        """
    ),
    md(
        """
        ## Related Work

        **Question: What similar work exists, and how is our project different?**  
        **Answer:** The three most similar research lines study particulate matter/depression, neighborhood environment/mental health, and U.S. environmental exposure/mental-health outcomes. Our difference is that we build a U.S. county-year machine-learning panel and combine supervised next-year prediction with unsupervised county profiling.

        """
        + simple_table(
            ["Study / resource", "1-2 sentence summary", "Difference from this project"],
            [
                [
                    "Park et al., PM2.5/PM10 and depression risk in KLoSA",
                    "This study found that prolonged particulate exposure was associated with elevated depression risk among middle-aged and older adults in South Korea.",
                    "It is individual/cohort-based and non-U.S.; our project is U.S. county-level and predictive/exploratory rather than causal.",
                ],
                [
                    "Lei et al., neighborhood environment and mental health in China",
                    "This work links perceived pollution, neighborhood conditions, and socioeconomic status to mental health outcomes.",
                    "Our project uses measured AQI/climate variables and ML clustering instead of perception-based neighborhood measures.",
                ],
                [
                    "Werder et al., Gulf Long-Term Follow-up Study",
                    "This U.S.-based study examines PM2.5, greenspace, and depression in the Southeastern United States.",
                    "Our project expands across U.S. counties and adds supervised next-year prediction plus unsupervised county profiling.",
                ],
            ],
        )
    ),
    md(
        f"""
        ## Data Sources

        **Question: Where are the data from, what formats did they use, what variables matter, how many records did we use, and what time period is covered?**  
        **Answer:** The final enriched panel contains **{panel_rows} county-year rows**, **{panel_cols} columns**, and **{county_count} county/county-equivalent GEOIDs** from **{year_min}-{year_max}**. Data are merged by five-digit county GEOID. The panel contains {state_count} state/DC labels in the final enriched file. Daily AQI monitor-derived features are available for about **{daily_coverage:.1f}%** of rows before imputation, while NOAA climate features cover about **{noaa_coverage:.1f}%** of rows.

        """
        + simple_table(
            ["Source", "Format/location", "Important variables", "Coverage / role"],
            [
                ["CDC PLACES", "data.cdc.gov CSV", "FMD prevalence, lower/upper confidence intervals", "Annual county-level mental-health outcome"],
                ["EPA AirData annual", "EPA CSV", "Days with AQI, Max AQI, Median AQI, pollutant-defining days", "Annual county air-quality predictors"],
                ["EPA daily AQI", "EPA ZIP/CSV", "Daily AQI mean/std/p90/max, days above 100/150/200", "Daily exposure variability and extreme-event predictors; sparse monitor coverage"],
                ["ACS 5-year tables", "Census bulk/API files", "Income, poverty, unemployment, education, insurance, industry composition", "Socioeconomic and health-access controls"],
                ["NOAA Climate at a Glance", "JSON/CSV-derived panel", "Annual temperature, precipitation, historical anomalies", "County climate context"],
                ["Census county boundaries", "Shapefile ZIP", "County geometries", "Mapping and residual/cluster visualization"],
            ],
        )
    ),
    md(
        """
        ## Feature Engineering

        **Question: How did we get from raw data to final ML features?**  
        **Answer:** We merged CDC PLACES, EPA AirData, ACS, NOAA, and Census geography by county GEOID; cleaned sentinel values; imputed missing numeric model inputs; engineered next-year FMD by shifting each county's FMD forward one year; standardized numeric features where needed; and excluded FMD/confidence intervals from clustering.

        **Question: How did we handle noisy or missing data?**  
        **Answer:** The EDA showed that daily AQI features are structurally missing in many counties because EPA monitors are sparse. We retained these features but imputed missing numeric values inside modeling pipelines and interpreted daily-AQI results cautiously. NOAA coverage was near-complete, while ACS and PLACES were harmonized to a common county-year panel.
        """
    ),
    md(
        """
        ### Integration of Jaeah's EDA Work

        **Question: How did Jaeah's exploratory work feed into the final project?**  
        **Answer:** Jaeah's EDA notebook informed the data-quality checks, rate engineering, environmental/health framing, and unsupervised county-profiling direction. Her notebook is included at `notebooks/jaeah_eda.ipynb`.

        """
        + simple_table(
            ["Jaeah EDA component", "What it checked", "How it is incorporated here"],
            [
                [
                    "Missingness audit",
                    "Examined AQI missingness and whether merged rows had systematic gaps.",
                    "The report explicitly discusses sparse daily AQI coverage and uses imputation rather than dropping monitor-sparse counties.",
                ],
                [
                    "Geographic coverage checks",
                    "Checked state/geography representation and possible Puerto Rico/Hawaii/coverage issues.",
                    "The final pipeline reports county-year coverage, maps residuals, and treats geographic patterns as exploratory rather than causal.",
                ],
                [
                    "Feature engineering rates",
                    "Converted raw poverty/unemployment counts into intensity-style measures to avoid county-size bias.",
                    "The final feature-engineering section emphasizes rates, standardized predictors, and leakage-safe target construction.",
                ],
                [
                    "Univariate and bivariate EDA",
                    "Explored AQI distributions, socioeconomic skew, FMD outliers, environmental justice, and income/AQI/FMD relationships.",
                    "Those exploratory patterns motivate the combined pollution + socioeconomic + climate feature representation and the cautious weak-signal interpretation.",
                ],
                [
                    "Spatial and temporal framing",
                    "Explored how patterns varied over time and across places.",
                    "The final report includes temporal next-year prediction, geographic residual mapping, and unsupervised county-profile visualizations.",
                ],
            ],
        )
    ),
    md(
        """
        ### Feature Families and Leakage Controls

        """
        + simple_table(
            ["Feature family", "Examples", "Role / leakage control"],
            [
                ["Identifiers", "geoid, county_name, state_name, year", "Merge/split/reporting keys; not substantive predictors."],
                ["FMD outcome", "mental_health_prevalence, lower_ci, upper_ci, next_year_fmd", "Supervised target or held-out cluster outcome; excluded from unsupervised clustering."],
                ["Annual AQI", "Max AQI, Median AQI, category days, pollutant days", "Current-year exposure predictors."],
                ["Daily AQI", "daily_aqi_std, daily_aqi_p90, threshold days", "Exposure variability and extreme-event predictors with sparse monitor coverage."],
                ["ACS socioeconomic", "median_income, population, poverty_count, unemployed_count", "Community vulnerability controls."],
                ["Education/health/industry", "pct_uninsured, pct_bachelors_or_higher, pct_manufacturing", "Access, educational attainment, and industrial-trait predictors."],
                ["Climate", "annual_avg_temp_f, annual_precip_inches, anomalies", "Environmental context beyond AQI."],
            ],
        )
    ),
    md(
        """
        ## Part A. Supervised Learning

        ### Methods

        **Question: What was the supervised workflow?**  
        **Answer:** We framed supervised learning as regression: predict year *t+1* FMD from year *t* county-level features. The final holdout used 2022 features to predict 2023 FMD.

        **Question: Which model families did we explore and why?**  
        **Answer:** We used at least three diverse model families: a Dummy Regressor baseline, ElasticNet regularized linear regression, Random Forest bagged trees, and Gradient Boosting sequential trees. These cover baseline, linear, and nonlinear tree-ensemble mechanisms.

        **Question: How did we tune models?**  
        **Answer:** We used grouped cross-validation by feature year on the training period, then evaluated the chosen models on the 2022-to-2023 temporal holdout. Hyperparameter exploration included ElasticNet alpha/l1-ratio, Random Forest feature sampling and leaf size, and Gradient Boosting learning rate/depth/estimators.
        """
    ),
    md(
        """
        ### Supervised Evaluation: Overall Results

        **Question: Which metrics did we use and why?**  
        **Answer:** We report RMSE and MAE because FMD is continuous and measured in percentage points. RMSE penalizes large misses, MAE is easier to interpret as average absolute percentage-point error, and R² shows whether the model explains more variation than a mean baseline.

        **Question: How did the model families compare using CV mean and standard deviation?**  
        **Answer:** The Random Forest had the best holdout RMSE and the best CV RMSE mean, but the improvement over baseline was modest and uncertainty across year-based folds was large.

        """
        + simple_table(
            ["Model", "Holdout RMSE", "Holdout MAE", "Holdout R2", "CV RMSE mean", "CV RMSE SD", "CV R2 mean", "CV R2 SD"],
            metrics_rows,
        )
    ),
    md(
        f"""
        ![Figure 1. Supervised model comparison with CV mean and SD.]({FIG}/figure_01_supervised_model_comparison.png)

        ![Figure 2. Predicted vs. actual FMD and residual distribution.]({FIG}/figure_02_predictions_residuals.png)

        ![Figure 3. Geographic residual map from project Census boundaries and model predictions.]({FIG}/figure_03_residual_map.png)
        """
    ),
    md(
        """
        ### Feature Importance and Ablation

        **Question: Which features contributed to the best supervised model?**  
        **Answer:** Random Forest feature importance ranked education and climate variables highly, including bachelor-degree share, temperature anomaly, lower educational attainment, high-school attainment, annual temperature, and median income. AQI features were present but did not dominate the model.

        **Question: What did the ablation analysis show?**  
        **Answer:** Removing education and health-access features increased RMSE the most. Some pollution/climate feature removals did not worsen holdout RMSE in this split, which supports the cautious conclusion that current county-level AQI variables are not strong standalone predictors of next-year FMD.

        """
        + simple_table(["Removed feature family", "Features removed", "Holdout RMSE", "RMSE delta"], ablation_rows)
    ),
    md(
        f"""
        ![Figure 4. Random Forest feature importances.]({FIG}/figure_04_rf_feature_importance.png)

        ![Figure 5. Random Forest feature-family ablation.]({FIG}/figure_05_rf_ablation.png)
        """
    ),
    md(
        """
        ### Sensitivity, Tradeoffs, and Failure Analysis

        **Question: How sensitive was the best model to hyperparameters?**  
        **Answer:** Random Forest performance was sensitive to leaf size and feature sampling. Smaller leaves with square-root feature sampling performed best; larger leaves were more stable but less accurate.

        """
        + simple_table(["min_samples_leaf", "max_features", "Holdout RMSE", "Holdout R2"], sensitivity_rows)
    ),
    md(
        f"""
        ![Figure 6. Random Forest hyperparameter sensitivity.]({FIG}/figure_06_rf_sensitivity.png)
        """
    ),
    md(
        """
        **Question: What tradeoffs did we identify?**  
        **Answer:** Random Forest offered the best accuracy but lower interpretability than ElasticNet. More flexible trees captured nonlinear structure but still compressed predictions toward the mean. The most important practical tradeoff is weak predictive improvement versus the risk of overinterpreting county-level associations.

        **Question: Where did prediction fail, and why might it have failed?**  
        **Answer:** The largest errors were mostly high-FMD counties that the model underpredicted. These failures likely reflect missing local variables such as behavioral-health infrastructure, rurality, disability burden, opioid-related distress, social isolation, and monitor coverage limitations.

        """
        + simple_table(["County", "State", "Actual FMD", "Prediction", "Residual", "Failure category"], failure_rows)
    ),
    md(
        """
        **Question: What future improvements might address these failures?**  
        **Answer:** Add provider density, rurality/urbanicity, opioid burden, disability prevalence, greenspace, disaster exposure, and finer monthly/daily exposure windows. The model needs richer local context to handle high-distress tails.
        """
    ),
    md(
        """
        ## Part B. Unsupervised Learning

        ### Methods

        **Question: What was the unsupervised workflow?**  
        **Answer:** Our unsupervised analysis asked whether counties fall into distinct socio-environmental clusters. FMD was intentionally excluded from clustering so that DBSCAN and K-Means discovered structure using only environmental, climate, socioeconomic, healthcare access, education, and industry characteristics. We then examined FMD after clustering as a held-out descriptive outcome. This design prevents the cluster labels from simply reproducing the mental-health target and makes any FMD differences across clusters an external comparison rather than a clustering input. Before clustering, numeric county-profile features were harmonized and standardized with StandardScaler so variables measured on different scales contributed comparably. The final reproducible report pipeline used PCA for the two-dimensional diagnostic embedding and cluster visualizations; earlier exploratory notebooks tested UMAP/PCA options, but the report figures and sensitivity table are generated from the PCA-based pipeline for reproducibility.

        **Question: Which unsupervised methods did we use and why?**  
        **Answer:** DBSCAN and K-Means were selected as complementary methods. DBSCAN was selected because it does not require pre-specifying the number of clusters and can identify outlier counties as noise. K-Means was used as a centroid-based comparison because it assigns every county to exactly one cluster, making it useful for interpretable county archetypes.

        **Question: How did we tune or explore unsupervised hyperparameters?**  
        **Answer:** In the final reproducible pipeline, DBSCAN searched exactly 70 parameter combinations: 14 `eps` values from `np.round(np.linspace(0.15, 2.0, 14), 2)` multiplied by five `min_samples` values `{5, 10, 20, 35, 50}`. The selected DBSCAN setting was `eps = 1.43` and `min_samples = 5`. K-Means evaluated `k in {2, 3, 4, 5, 6}` and selected `k = 2`, which had the highest silhouette score (0.89 on the PCA embedding; 0.75 on the scaled feature matrix). The full unsupervised search output therefore contains 75 rows: 70 DBSCAN settings plus 5 K-Means settings.\n\n**Reproducibility references:** [scripts/03_modeling/generate_rubric_analyses.py](https://github.com/sboettch/SIADS696-Team7-Final/blob/main/scripts/03_modeling/generate_rubric_analyses.py#L309-L365) implements the DBSCAN and K-Means searches; [outputs/modeling/rubric_completion/unsupervised_method_search.csv](https://github.com/sboettch/SIADS696-Team7-Final/blob/main/outputs/modeling/rubric_completion/unsupervised_method_search.csv) stores the 70 DBSCAN rows and 5 K-Means rows; [scripts/04_reporting_visualizations/create_reproducible_visualizations_notebook.py](https://github.com/sboettch/SIADS696-Team7-Final/blob/main/scripts/04_reporting_visualizations/create_reproducible_visualizations_notebook.py#L320-L348) generates Figure 11.

        """
        + simple_table(
            ["Method", "Selected parameters", "Clusters", "Noise %", "Silhouette embedding", "Silhouette scaled features"],
            unsup_rows,
        )
    ),
    md(
        """
        ### Unsupervised Evaluation

        **Question: Which unsupervised metrics did we use and why?**  
        **Answer:** We used silhouette scores to measure cluster separation, noise rate for DBSCAN, cluster counts/sizes for interpretability, and held-out FMD ANOVA to evaluate whether clusters formed without FMD were associated with mental-distress differences.

        """
        + simple_table(["Method", "F statistic", "p-value", "Groups"], anova_rows)
    ),
    md(
        f"""
        **Question: What are the two visualizations for DBSCAN?**  
        **Answer:** Figure 7 shows DBSCAN cluster separation on the PCA embedding. Figure 8 shows DBSCAN cluster profiles across average AQI, health access, education, temperature anomaly, and industry composition.

        ![Figure 7. DBSCAN clusters on PCA embedding.]({FIG}/figure_07_dbscan_pca_scatter.png)

        ![Figure 8. DBSCAN cluster profiles.]({FIG}/figure_08_dbscan_cluster_profile.png)

        **Question: What are the two visualizations for K-Means?**  
        **Answer:** Figure 9 shows K-Means cluster separation on the PCA embedding. Figure 10 shows K-Means cluster profiles using the same variables as DBSCAN, allowing direct comparison.

        ![Figure 9. K-Means clusters on PCA embedding.]({FIG}/figure_09_kmeans_pca_scatter.png)

        ![Figure 10. K-Means cluster profiles.]({FIG}/figure_10_kmeans_cluster_profile.png)
        """
    ),
    md(
        """
        **Question: What was the unsupervised sensitivity analysis?**  
        **Answer:** We evaluated DBSCAN across 70 `eps`/`min_samples` configurations and K-Means across 5 candidate `k` values, for 75 total unsupervised search rows in the saved output. K-Means `k=2` had the strongest silhouette score. DBSCAN showed high sensitivity to `eps`, with larger `eps` values generally producing fewer clusters and lower noise.

        """
        + simple_table(
            ["Method", "Candidate parameters", "Clusters", "Noise %", "Silhouette embedding", "Silhouette scaled features"],
            search_rows,
        )
    ),
    md(
        f"""
        ![Figure 11. DBSCAN and K-Means unsupervised sensitivity search: 70 DBSCAN settings and 5 K-Means settings.]({FIG}/figure_11_unsupervised_parameter_search.png)
        """
    ),
    md(
        """
        ## Discussion

        **Question: What did we learn from Part A?**  
        **Answer:** County-level environmental, climate, and socioeconomic data contain some predictive signal, but not enough for reliable next-year FMD forecasting. The best model modestly improved over baseline, but large errors remained in high-FMD counties.

        **Question: What surprised us in Part A?**  
        **Answer:** The weak holdout R² was surprising after enriching the dataset. Education, health access, and climate variables were more influential than expected, while AQI variables did not dominate prediction.

        **Question: What challenges did we encounter in Part A, and how did we respond?**  
        **Answer:** The main challenges were temporal leakage risk, sparse daily AQI coverage, and county-level aggregation. We responded by shifting the target forward within counties, using a temporal holdout, imputing sparse numeric features, and making cautious claims.

        **Question: How would we extend Part A with more time?**  
        **Answer:** Add healthcare provider density, rurality, opioid burden, disability prevalence, greenspace, disaster exposure, and monthly/daily exposure windows.

        **Question: What did we learn from Part B?**  
        **Answer:** Most counties occupy one broad socio-environmental space, while smaller groups/outliers differ structurally. DBSCAN is better for outlier detection, while K-Means is better for simple partitioning.

        **Question: What surprised us in Part B?**  
        **Answer:** The clusters were highly imbalanced, meaning the available county-level features did not form clean, evenly sized archetypes.

        **Question: What challenges did we encounter in Part B, and how did we respond?**  
        **Answer:** DBSCAN was sensitive to parameter choices and often produced one dominant cluster. We responded by comparing it to K-Means, reporting sensitivity results, and treating cluster interpretation as exploratory.

        **Question: How would we extend Part B with more time?**  
        **Answer:** Add richer social determinants, rurality/urbanicity classes, healthcare infrastructure, and possibly spatially constrained clustering or regional subgroup analyses.
        """
    ),
    md(
        """
        ## Ethical Considerations

        **Question: What ethical issues arise for Part A supervised prediction?**  
        **Answer:** County-level predictions could stigmatize communities or be misused as individual-level mental-health risk scores. They should be framed only as planning signals and paired with local expertise, uncertainty communication, and community input.

        **Question: What ethical issues arise for Part B unsupervised clustering?**  
        **Answer:** Cluster labels could be misread as rankings or causal categories. They should not be used to withdraw resources or blame communities. Clusters are exploratory summaries of observed county features, not definitive labels of community need or cause.
        """
    ),
    md(
        """
        ## Statement of Work

        **Question: What did each team member contribute?**  
        **Answer:** Each member contributed to data work, modeling, interpretation, and final synthesis, with the following primary responsibilities.

        """
        + simple_table(
            ["Team member", "Primary contributions"],
            [
                ["Jaeah Kim", "Exploratory data analysis, missingness and coverage checks, feature-engineering insight, unsupervised learning analysis support, clustering interpretation."],
                ["Kyle Rodriguez", "Visualization support, supervised and unsupervised evaluation, repository cleanup, data gathering, model interpretation, report synthesis."],
                ["Sophia Boettcher", "Dataset integration, imputation workflow, supervised and unsupervised baselines, external enrichment, final report drafting and rubric alignment."],
                ["All team members", "EDA, data cleaning, modeling review, final interpretation, and presentation/report synthesis."],
            ],
        )
    ),
    md(
        """
        ## References

        Centers for Disease Control and Prevention. (n.d.). *PLACES: Local Data for Better Health*. https://www.cdc.gov/places

        Lei, K., Yang, J., & Ke, X. (2025). The impact of neighborhood environment on the mental health: Evidence from China. *Frontiers in Public Health, 12*, 1452744. https://doi.org/10.3389/fpubh.2024.1452744

        National Oceanic and Atmospheric Administration. (n.d.). *Climate at a Glance*. National Centers for Environmental Information. https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance

        Park, H., Kang, C., AiMS-CREATE Team, & Kim, H. (2024). Particulate matters (PM2.5, PM10) and the risk of depression among middle-aged and older population: Analysis of the Korean Longitudinal Study of Aging (KLoSA), 2016-2020 in South Korea. *Environmental Health, 23*(1), Article 4. https://doi.org/10.1186/s12940-023-01043-1

        U.S. Census Bureau. (2009-2024). *American Community Survey 5-Year Estimates* [Data set]. Census Data API. https://api.census.gov/data

        U.S. Census Bureau. (2023). *Cartographic Boundary Files: County Shapefile*. https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html

        U.S. Environmental Protection Agency. (2026). *Air Quality System (AQS) Data Mart: AirData* [Data set]. https://aqs.epa.gov/aqsweb/airdata/download_files.html

        Werder, E., Lawrence, K., Deng, X., Jackson II, W. B., Christenbury, K., Buller, I., Engel, L., & Sandler, D. (2024). Residential air pollution, greenspace, and adverse mental health outcomes in the U.S. Gulf Long-term Follow-up Study. *Science of the Total Environment, 946*, 174434. https://doi.org/10.1016/j.scitotenv.2024.174434
        """
    ),
    md(
        """
        ## Project Submission Links

        **Question: Where is the GitHub repository?**  
        **Answer:** Insert the final GitHub URL here after the repository is pushed.

        **Question: Where is the Google Doc version with comments enabled?**  
        **Answer:** Insert the final Google Doc URL here after the report notebook/PDF and Google Doc are finalized.
        """
    ),
    md(
        """
        ## Appendix A. Complete Modeling Feature List

        **Question: What final features were used in supervised modeling?**  
        **Answer:** The following features appear in the final Random Forest feature-importance file and represent the final supervised modeling predictors used for the rubric-completion analysis.

        """
        + simple_table(["Feature", "Feature family", "RF importance"], feature_rows)
    ),
    md(
        """
        ## Appendix B. Figure Provenance

        **Question: Are report images generated from project data?**  
        **Answer:** Yes. The figures in this notebook are loaded from `outputs/visualizations/reproducible_report_figures/`, and that folder is regenerated by `notebooks/06_visualization_generation/Final_Report_Reproducible_Visualizations.ipynb` using repository data and model-output CSVs. The figure manifest is `outputs/visualizations/reproducible_report_figures/figure_manifest.csv`.
        """
    ),
]

nb = nbf.v4.new_notebook(
    cells=cells,
    metadata={
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
)

OUT.parent.mkdir(parents=True, exist_ok=True)
nbf.write(nb, OUT)
print(OUT)

